config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  
  resources :customers

  resources :menus

  resources :orders do
    get :autocomplete_menu_name, on: :collection 
    collection do
      get :update_type
      get :increment
      get :decrement
      get :destroy_item
      get :add_item
    end
  end
  
  devise_for :users

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer 
	has_many :order_items
	has_many :menus, through: :order_items
	accepts_nested_attributes_for :order_items, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	autocomplete :menu, :name, extra_data: [:price, :code]
	before_filter :set_items, only: [:update_type, :create, :add_item, :update, :increment, :decrement, :destroy_item]
	helper_method [:subtotal, :tax, :tip, :total]

	def set_items
		@order = Order.find(session[:order_id])
		@order_items = @order.order_items
	end

	def index
    @orders = Order.all
  end

  def show
  end

	def new
		@order = Order.find(session[:order_id])
		@order_items = @order.order_items
	rescue ActiveRecord::RecordNotFound
		@order = Order.create
		@order_items = @order.order_items
		session[:order_id] = @order.id
	end

	def create
		@order.update(subtotal: subtotal)
		@order.update(tip: tip)
		@order.update(tax: tax)
		@order.update(total: total)
		@order.save
		session.delete(:order_id)
		session.delete(:customer_id)
		respond_to do |format|
			format.html { redirect_to action: 'index'}
		end
	end

	def update
		if find_customer_param.has_key?(:find_customer)
			@customer = Customer.where(phone: customer_params[:phone]).first
			if @customer.nil?
				respond_to do |format|
					format.js {refresh}
				end
			else
				session[:customer_id] = @customer.id
				respond_to do |format|
					format.html { redirect_to action: 'new'}
					format.js { refresh }
				end
			end
		end
	end

	def update_type
		respond_to do |format|
			format.html { redirect_to action:'new'}
			format.js {refresh}
		end
	end

	def add_item
		@order_item = OrderItem.new(order_item_params)
		@order_item.order_id = session[:order_id]
		@order_item.save
		respond_to do |format|
			format.html { redirect_to action: 'new'}
			format.js { refresh }
		end
	end

	def destroy_item
		OrderItem.destroy(order_item_id_param)
		respond_to do |format|
				format.html { redirect_to action: 'new'}
				format.js { refresh}
		end
	end

	def increment
		@order_item = OrderItem.find(order_item_id_param)
		@order_item.increment! :quantity
		respond_to do |format|
				format.html { redirect_to action: 'new'}
				format.js { refresh}
		end
	end

	def decrement
		@order_item = OrderItem.find(order_item_id_param)
		@order_item.decrement! :quantity
		respond_to do |format|
				format.html { redirect_to action: 'new'}
				format.js { refresh}
		end
	end

	def subtotal
		@order = Order.find(session[:order_id])
		@order_items = @order.order_items
		@total = 0
		@order_items.each do |item|
			@total += item.quantity * item.unit_price
		end
	  @total
	end

	def tax
		subtotal * 0.18
	end

	def tip
		subtotal * 0.10
	end

	def total
		subtotal + tax + tip
	end

	def refresh
		render(file: 'orders/reload.js.erb')
	end

private
	def order_item_id_param
		params.require(:order_item_id)
	end

	def order_item_params
		params.require(:order_item).permit(:id, :menu_id, :code, :name, :unit_price, :quantity)
	end

	def find_customer_param
		params.permit(:find_customer)
	end

	def customer_params
		params.require(:customer).permit(:id, :firstname, :lastname, :phone, :address)
	end

	def order_params
		params.require(:order).permit(:id, :customer_id)
	end

end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/orders/_form.html.erb
<div class="order-type">
  <%= render 'order_type_buttons' %>
</div>
<div class="add_order_item">
  <%= render 'order_item_fields' %>
</div>
<div class ="added_items">
  <%= render 'added_items' %>
</div>
<div class="order_totals">
  <%= render 'order_totals' %>
</div>

app/views/orders/_order_item_fields.html.erb
<h4> Add Items </h4>

<table width='700'>
<%= form_for :order_item, url: url_for(controller: 'orders', action:'add_item'), method: 'get', format: :js, remote: true do |f| %>

	<%= f.hidden_field :menu_id %>

  <tr>

    <td>
  <div class="field">
  	<%= f.label "Code" %>
    <%= f.text_field :code %>
  </div>
</td>
<td>

  <div class="field">
  	<%= f.label :name %>
    <%= f.autocomplete_field :name, autocomplete_menu_name_orders_path, 
      		update_elements: {id: '#order_item_menu_id', price: '#order_item_unit_price', code: '#order_item_code'}  %>
  </div>
</td>
<td>

  <div class="field">
  	<%= f.label :unit_price %>  
    <%= f.text_field :unit_price, readonly: true%>
  </div>
</td>

<td>
  <div class="field">
  	<%= f.label :quantity %>  
    <%= f.number_field :quantity %>
  </div>

</td>

</tr>
<tr>
  <td>
  <div class="actions">
      <%= f.submit "Add Item", class: 'order-form-submit' %>
  </div>
</td>
</tr>
<% end %>

</table>

app/views/orders/index.html.erb
<div class='order-history'>
<h1>Order History</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>Customer ID</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.created_at %></td>
        <td><%= order.type %></td>
        <td><%= order.customer_id %></td>
        <td><%= number_to_currency(order.total) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/orders/new.html.erb
<div class="order-form">
<h4> Order #<%= @order.id %> created at <%= @order.created_at.in_time_zone('La Paz') %></h4>
<%= render 'form' %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Listing</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Menu Code</th>
      <th>Product Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.menu_id %></td>
        <td><%= order_item.name %></td>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.total_price %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>